TRUNCATE TABLE station;
TRUNCATE TABLE line;
TRUNCATE TABLE section;

ALTER TABLE station ALTER COLUMN id RESTART WITH 1;
ALTER TABLE line ALTER COLUMN id RESTART WITH 1;
ALTER TABLE section ALTER COLUMN id RESTART WITH 1;
