DELETE
FROM EDGE;
DELETE
FROM STATION;
DELETE
FROM LINE;
ALTER TABLE STATION
    ALTER COLUMN id RESTART WITH 1;
ALTER TABLE LINE
    ALTER COLUMN id RESTART WITH 1;
ALTER TABLE EDGE
    ALTER COLUMN id RESTART WITH 1;