TRUNCATE TABLE STATION;
ALTER TABLE STATION ALTER COLUMN id RESTART WITH 1;

TRUNCATE TABLE LINE;
ALTER TABLE LINE ALTER COLUMN id RESTART WITH 1;

TRUNCATE TABLE SECTION;
ALTER TABLE SECTION ALTER COLUMN id RESTART WITH 1;